### ISSUE TITLE
Tabs component slightly misaligned on small screens.

### ISSUE THREAD

**Issue by nickcolley** [alphagov/frontend#1755]
Screenshot of current issue:

<img width="395" alt="screen shot 2019-02-11 at 15 34 44" src="https://user-images.githubusercontent.com/2445413/52573754-b7d52900-2e12-11e9-9993-16b807acc39f.png">

What it should look like:

<img width="397" alt="screen shot 2019-02-11 at 15 39 38" src="https://user-images.githubusercontent.com/2445413/52574022-4649aa80-2e13-11e9-82e4-915cdd28ce37.png">

While the tabs component is in the govuk_publishing_components gem, I think the issue is that global styles in this application are leaking into the component.

This has been tried to resolved with the following CSS:

```css
.content-block .govuk-tabs__list {
    padding: 0;
    margin: 0
}

.content-block .govuk-tabs__list-item {
    list-style: none;
    padding-left: 0;
    margin: 0
}
```

But does not account for mobile, which results in the list styles being slightly off.

## Steps to reproduce

1. Go to https://www.gov.uk/apply-renew-passport#more-information
2. Make the viewport small, tabs should change into a contents list
3. Notice that the contents list is within the gutter of the page

## Recommendation

Ideally we'd ensure that the `.content-block` is not around component code.
